apiVersion: apps/v1
kind: Deployment
metadata:
  name: imagepull-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imagepull-demo
  template:
    metadata:
      labels:
        app: imagepull-demo
    spec:
      containers:
      - name: nginxx
        image: nginx:latest
        ports:
        - containerPort: 80
